type: S3
config:
  bucket: "s3teste"
  endpoint: "http://172.20.175.146:9000"
  region: "bb"  
  access_key: "minioadmin"
  insecure: true
  # signature_version2: true
  secret_key: "minioadmin"